
name = input("What is the name of the gift giver?")
present = input("What is the present they gave you?")
print()
age = input("How old were you on your birthday?")
yourName = input("What is your name?")
print("Dear " + name + ", ")
print("")
print("Thank you for the " + present + ". ")
print("I really like it. I can't believe ")
print("I am already " + age + " years old, but ")
print("it does not feel much different than being ")
print(str(int(age)-1) + ".")
print("")
print("Sincerely,")
print("")
print(yourName)
